# Generated by Django 2.0.7 on 2018-07-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MDP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mdp_id', models.IntegerField()),
                ('mdp_name', models.CharField(max_length=50)),
                ('reference', models.CharField(max_length=50)),
                ('dissimilarity', models.CharField(max_length=50)),
                ('ordinal', models.CharField(max_length=50)),
                ('cartesian', models.CharField(max_length=50)),
                ('ne_structures', models.CharField(max_length=50)),
                ('categorical', models.CharField(max_length=50)),
                ('linearity', models.CharField(max_length=50)),
                ('supervision', models.CharField(max_length=50)),
                ('multi_level', models.CharField(max_length=50)),
                ('locality', models.CharField(max_length=50)),
                ('steerability', models.CharField(max_length=50)),
                ('stability', models.CharField(max_length=50)),
                ('out_of_core_data', models.CharField(max_length=50)),
                ('complexity', models.CharField(max_length=50)),
            ],
        ),
    ]
