# Generated by Django 2.0.7 on 2019-06-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp', '0001_testing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdp',
            name='reference',
            field=models.CharField(max_length=100),
        ),
    ]
