# Generated by Django 2.0.7 on 2018-07-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp', '0002_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mdp',
            name='id',
        ),
        migrations.AlterField(
            model_name='mdp',
            name='mdp_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
