# Generated by Django 2.0.7 on 2018-07-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp', '0003_auto_20180707_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='languages',
            name='r',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
