# Generated by Django 2.0.7 on 2018-07-09 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp', '0005_auto_20180707_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='TS',
            new_name='ts',
        ),
        migrations.AlterField(
            model_name='qualitymeasure',
            name='best',
            field=models.IntegerField(),
        ),
    ]
