# Generated by Django 2.0.7 on 2019-06-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp', '0005_testing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mdp',
            name='complexity_name',
        ),
        migrations.RemoveField(
            model_name='task',
            name='input_space_name',
        ),
        migrations.RemoveField(
            model_name='task',
            name='output_space_name',
        ),
        migrations.AddField(
            model_name='enrichment',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Comments/Description'),
        ),
        migrations.AddField(
            model_name='languages',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Comments/Description'),
        ),
        migrations.AddField(
            model_name='mdp',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Comments/Description'),
        ),
        migrations.AddField(
            model_name='qualitymeasure',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Comments/Description'),
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Comments/Description'),
        ),
        migrations.AddField(
            model_name='variants',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Comments/Description'),
        ),
        migrations.AlterField(
            model_name='languages',
            name='cplusplus',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='C++'),
        ),
        migrations.AlterField(
            model_name='languages',
            name='java',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='languages',
            name='javascript',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='languages',
            name='matlab',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='languages',
            name='python',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='languages',
            name='r',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mdp',
            name='cartesian',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mdp',
            name='categorical',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mdp',
            name='dissimilarity',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mdp',
            name='linearity',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mdp',
            name='locality',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mdp',
            name='multi_level',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mdp',
            name='ne_structures',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Neighbouring Structures'),
        ),
        migrations.AlterField(
            model_name='mdp',
            name='ordinal',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mdp',
            name='out_of_core_data',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mdp',
            name='reference',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mdp',
            name='stability',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mdp',
            name='steerability',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mdp',
            name='supervision',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='qualitymeasure',
            name='correlation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='qualitymeasure',
            name='dissimilarity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='qualitymeasure',
            name='geometric',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='qualitymeasure',
            name='globall',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Global'),
        ),
        migrations.AlterField(
            model_name='qualitymeasure',
            name='homology',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='qualitymeasure',
            name='local',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='qualitymeasure',
            name='probability',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='qualitymeasure',
            name='rank',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='qualitymeasure',
            name='set_difference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
