# Generated by Django 2.0.7 on 2018-07-10 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp', '0006_auto_20180709_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdp',
            name='mdp_fullname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
