# Generated by Django 2.0.7 on 2019-06-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp', '0006_testing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdp',
            name='complexity',
            field=models.CharField(max_length=500, verbose_name='Complexity (MathJax)'),
        ),
        migrations.AlterField(
            model_name='qualitymeasure',
            name='rangee',
            field=models.CharField(max_length=100, verbose_name='Range (MathJax)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='input_space',
            field=models.CharField(max_length=100, verbose_name='Input Space (MathJax)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='output_space',
            field=models.CharField(max_length=100, verbose_name='Output Space (MathJax)'),
        ),
    ]
