# Generated by Django 2.0.7 on 2019-06-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp', '0007_testing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrichment',
            name='enrichment_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='languages',
            name='language_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mdp',
            name='mdp_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='qualitymeasure',
            name='measure_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='variants',
            name='variant_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
