# Generated by Django 2.0.7 on 2018-07-10 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp', '0007_mdp_mdp_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='variants',
            name='variant_reference1',
            field=models.CharField(max_length=50),
        ),
    ]
