# Generated by Django 2.0.7 on 2018-07-12 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdp', '0008_variants_variant_reference1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variants',
            name='variant_reference1',
        ),
    ]
