# Generated by Django 2.0.7 on 2019-06-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp', '0008_testing'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='children',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='parent',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
