# Generated by Django 2.0.7 on 2019-06-24 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp', '0009_testing'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomatedDisplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=100)),
                ('section_name', models.CharField(max_length=100)),
                ('property_name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=250)),
            ],
        ),
    ]
