# Generated by Django 2.0.7 on 2018-07-12 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp', '0009_remove_variants_variant_reference1'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdp',
            name='complexity_name',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qualitymeasure',
            name='rangee_name',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='input_space_name',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='output_space_name',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
