# Generated by Django 2.0.7 on 2019-06-24 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp', '0010_testing'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('employee_of', models.CharField(max_length=100, verbose_name='Institute/Employer')),
                ('email', models.CharField(max_length=200, verbose_name='Email address')),
            ],
        ),
    ]
