# Generated by Django 2.0.7 on 2019-06-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp', '0012_testing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='children',
        ),
        migrations.RemoveField(
            model_name='task',
            name='parent',
        ),
        migrations.AddField(
            model_name='task',
            name='child_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Fill this ID field with the integer(s) (space separated) corresponding to the desired parent (only in case the parent exists)'),
        ),
        migrations.AddField(
            model_name='task',
            name='parent_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fill this ID field only to list this as a parent with possible children'),
        ),
    ]
