# Generated by Django 2.0.7 on 2019-06-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp', '0013_testing'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_subset',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Enter ID(s) of the tasks (as a space separated set) into which this task is decomposed'),
        ),
    ]
