# Generated by Django 2.0.7 on 2019-06-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp', '0014_testing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='parent_id',
            field=models.IntegerField(blank=True, default=0, verbose_name='Fill this ID field only to list this as a parent with possible children'),
        ),
    ]
