# Generated by Django 2.0.7 on 2019-06-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp', '0015_testing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='child_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Fill this field to specify the tasks that inherit from the results obtained after performing this task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='parent_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fill this to specify the suggested tasks to be performed prior to this one'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_subset',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Specify the ID(s) of the tasks into which this main task is decomposed'),
        ),
    ]
