# Generated by Django 2.0.7 on 2019-07-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp', '0016_testing'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='THIS_IS_A_NEW_FIELD',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='New field'),
        ),
    ]
