# Generated by Django 2.0.7 on 2019-07-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp', '0017_testing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='THIS_IS_A_NEW_FIELD',
        ),
        migrations.AddField(
            model_name='mdp',
            name='reference_list',
            field=models.ManyToManyField(to='mdp.Reference'),
        ),
    ]
