# Generated by Django 2.0.7 on 2019-07-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp', '0018_testing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdp',
            name='reference_list',
            field=models.ManyToManyField(to='mdp.Reference', verbose_name='Reference List (click the plus icon to add a reference not currently present)'),
        ),
    ]
