# Generated by Django 2.0.7 on 2019-07-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp', '0019_testing'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandlingAbility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technique_handling_ability', models.CharField(max_length=2000)),
            ],
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='email',
            field=models.EmailField(max_length=200, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='mdp',
            name='reference_list',
            field=models.ManyToManyField(to='mdp.Reference'),
        ),
    ]
