# Generated by Django 2.0.7 on 2019-07-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp', '0020_testing'),
    ]

    operations = [
        migrations.CreateModel(
            name='MathJaxFormulas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mathjaxeqn', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='mdp',
            name='cartesian',
        ),
        migrations.RemoveField(
            model_name='mdp',
            name='categorical',
        ),
        migrations.RemoveField(
            model_name='mdp',
            name='complexity',
        ),
        migrations.RemoveField(
            model_name='mdp',
            name='dissimilarity',
        ),
        migrations.RemoveField(
            model_name='mdp',
            name='linearity',
        ),
        migrations.RemoveField(
            model_name='mdp',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='mdp',
            name='multi_level',
        ),
        migrations.RemoveField(
            model_name='mdp',
            name='ne_structures',
        ),
        migrations.RemoveField(
            model_name='mdp',
            name='ordinal',
        ),
        migrations.RemoveField(
            model_name='mdp',
            name='out_of_core_data',
        ),
        migrations.RemoveField(
            model_name='mdp',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='mdp',
            name='stability',
        ),
        migrations.RemoveField(
            model_name='mdp',
            name='steerability',
        ),
        migrations.RemoveField(
            model_name='mdp',
            name='supervision',
        ),
        migrations.AlterField(
            model_name='mdp',
            name='reference_list',
            field=models.ManyToManyField(to='mdp.Reference', verbose_name='List of References'),
        ),
    ]
