# Generated by Django 2.0.7 on 2019-07-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp', '0021_testing'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdp',
            name='cartesian',
            field=models.ManyToManyField(related_name='cartesian', to='mdp.HandlingAbility'),
        ),
        migrations.AddField(
            model_name='mdp',
            name='categorical',
            field=models.ManyToManyField(related_name='categorical', to='mdp.HandlingAbility'),
        ),
        migrations.AddField(
            model_name='mdp',
            name='complexity',
            field=models.ManyToManyField(to='mdp.MathJaxFormulas', verbose_name='Complexity (MathJax)'),
        ),
        migrations.AddField(
            model_name='mdp',
            name='dissimilarity',
            field=models.ManyToManyField(related_name='dissimilarity', to='mdp.HandlingAbility'),
        ),
        migrations.AddField(
            model_name='mdp',
            name='linearity',
            field=models.ManyToManyField(related_name='linearity', to='mdp.HandlingAbility'),
        ),
        migrations.AddField(
            model_name='mdp',
            name='locality',
            field=models.ManyToManyField(related_name='locality', to='mdp.HandlingAbility'),
        ),
        migrations.AddField(
            model_name='mdp',
            name='multi_level',
            field=models.ManyToManyField(related_name='multi_level', to='mdp.HandlingAbility'),
        ),
        migrations.AddField(
            model_name='mdp',
            name='ne_structures',
            field=models.ManyToManyField(related_name='ne_structures', to='mdp.HandlingAbility', verbose_name='Neighbouring Structures'),
        ),
        migrations.AddField(
            model_name='mdp',
            name='ordinal',
            field=models.ManyToManyField(related_name='ordinal', to='mdp.HandlingAbility'),
        ),
        migrations.AddField(
            model_name='mdp',
            name='out_of_core_data',
            field=models.ManyToManyField(related_name='out_of_core_data', to='mdp.HandlingAbility'),
        ),
        migrations.AddField(
            model_name='mdp',
            name='stability',
            field=models.ManyToManyField(related_name='stability', to='mdp.HandlingAbility'),
        ),
        migrations.AddField(
            model_name='mdp',
            name='steerability',
            field=models.ManyToManyField(related_name='steerability', to='mdp.HandlingAbility'),
        ),
        migrations.AddField(
            model_name='mdp',
            name='supervision',
            field=models.ManyToManyField(related_name='supervision', to='mdp.HandlingAbility'),
        ),
    ]
