# Generated by Django 2.0.7 on 2019-07-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp', '0022_testing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mathjaxformulas',
            name='mathjaxeqn',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
