# Generated by Django 2.0.7 on 2019-07-02 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdp', '0023_testing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AutomatedDisplay',
        ),
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'verbose_name': 'Team Data'},
        ),
        migrations.AlterModelOptions(
            name='enrichment',
            options={'verbose_name': 'Enrichments'},
        ),
        migrations.AlterModelOptions(
            name='handlingability',
            options={'verbose_name': 'Handling Abilities'},
        ),
        migrations.AlterModelOptions(
            name='languages',
            options={'verbose_name': 'Programming Languages'},
        ),
        migrations.AlterModelOptions(
            name='mathjaxformulas',
            options={'verbose_name': 'MathJax Formulae'},
        ),
        migrations.AlterModelOptions(
            name='mdp',
            options={'verbose_name': 'Projection Techniques'},
        ),
        migrations.AlterModelOptions(
            name='qualitymeasure',
            options={'verbose_name': 'Quality Measures'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Tasks'},
        ),
        migrations.AlterModelOptions(
            name='variants',
            options={'verbose_name': 'Variants'},
        ),
    ]
