# Generated by Django 2.0.7 on 2019-07-02 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mdp', '0024_testing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'verbose_name_plural': 'Team Data'},
        ),
        migrations.AlterModelOptions(
            name='enrichment',
            options={'verbose_name_plural': 'Enrichments'},
        ),
        migrations.AlterModelOptions(
            name='handlingability',
            options={'verbose_name_plural': 'Handling Abilities'},
        ),
        migrations.AlterModelOptions(
            name='languages',
            options={'verbose_name_plural': 'Programming Languages'},
        ),
        migrations.AlterModelOptions(
            name='mathjaxformulas',
            options={'verbose_name_plural': 'MathJax Formulae'},
        ),
        migrations.AlterModelOptions(
            name='mdp',
            options={'verbose_name_plural': 'Projection Techniques'},
        ),
        migrations.AlterModelOptions(
            name='qualitymeasure',
            options={'verbose_name_plural': 'Quality Measures'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterModelOptions(
            name='variants',
            options={'verbose_name_plural': 'Variants'},
        ),
    ]
