# Generated by Django 2.0.7 on 2019-07-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp', '0025_testing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='languages',
            name='cplusplus',
        ),
        migrations.RemoveField(
            model_name='languages',
            name='java',
        ),
        migrations.RemoveField(
            model_name='languages',
            name='javascript',
        ),
        migrations.RemoveField(
            model_name='languages',
            name='matlab',
        ),
        migrations.RemoveField(
            model_name='languages',
            name='mdp_id',
        ),
        migrations.RemoveField(
            model_name='languages',
            name='mdp_name',
        ),
        migrations.RemoveField(
            model_name='languages',
            name='python',
        ),
        migrations.RemoveField(
            model_name='languages',
            name='r',
        ),
        migrations.AddField(
            model_name='languages',
            name='language_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Programming Language'),
        ),
        migrations.AddField(
            model_name='mdp',
            name='langs_handled',
            field=models.ManyToManyField(to='mdp.Languages', verbose_name='Languages Handled'),
        ),
        migrations.RemoveField(
            model_name='languages',
            name='reference_list',
        ),
        migrations.AddField(
            model_name='languages',
            name='reference_list',
            field=models.ManyToManyField(max_length=300, to='mdp.Reference'),
        ),
    ]
