# Generated by Django 2.0.7 on 2019-07-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp', '0026_testing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languages',
            name='language_name',
            field=models.CharField(default='null for now', max_length=50, unique=True, verbose_name='Programming Language'),
            preserve_default=False,
        ),
    ]
