# Generated by Django 2.0.7 on 2019-07-02 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdp', '0027_testing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variants',
            name='mdp_id',
        ),
        migrations.AddField(
            model_name='mdp',
            name='tech_variants',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mdp',
            name='variant_refs',
            field=models.ManyToManyField(related_name='variantrefs', to='mdp.Reference'),
        ),
        migrations.DeleteModel(
            name='Variants',
        ),
    ]
