"""
Django settings for api_example project.

Generated by 'django-admin startproject' using Django 2.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GEOIP_PATH =os.path.join(BASE_DIR, 'geoip')



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'n)2e%(gfk4%9!2xq9zt$tbr7_crsk_lo6k^g*71q)9%-u=mopf'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'import_export',
    'django.contrib.staticfiles',
    'django_user_agents',
    'mdp',
    'tracking_analyzer'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_user_agents.middleware.UserAgentMiddleware',
]

ROOT_URLCONF = 'api_example.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['/home/db4mdp/templates/'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],

         'libraries':{
            'mdp_filters': 'mdp.templatetags.mdp_filters',

            }
        },
    },
]

WSGI_APPLICATION = 'api_example.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

# database_url = os.environ['DATABASE_URL']
#DATABASES = {
#'default': {
#        'ENGINE': 'django.db.backends.postgresql',
#        'ADAPTER': 'postgresql',
#        'NAME': 'postgres',
#        'USER': 'postgres',
#        'HOST': '/tmp',
#        'PORT': '5555'
#        }
#    }

DATABASES = {
'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'ADAPTER': 'postgresql',
        'NAME': 'rzowhigs',
        'USER': 'rzowhigs',
        'HOST': 'dumbo.db.elephantsql.com',
        'PASSWORD' : 'K-amH6uOaHUrGDgztWZOxaDaSSnXzUJp',
        'PORT': '5432'
        }
    }


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Chicago'

USE_I18N = True

USE_L10N = True

USE_TZ = True

IMPORT_EXPORT_USE_TRANSACTIONS = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

#For dev server. Otherwise static files wont update
STATIC_URL = '/Users/MAHE/db4mdp-master/db4mdp/static/'

STATICFILES_DIRS = [
	os.path.join(BASE_DIR, "static"),
	'/Users/MAHE/db4mdp-master/db4mdp/static/'
]

#For production

#STATIC_URL = '/home/db4mdp/static/'

#STATICFILES_DIRS = [
#	os.path.join(BASE_DIR, "static"),
#	'/home/db4mdp/static/'
#]
